steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    # Establecer permisos de ejecución para el comando vite
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        chmod +x node_modules/.bin/vite
        npm run build

images:
  - 'gcr.io/$PROJECT_ID/mercado-gaucho'
