steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

options:
  logs_bucket: gs://[logs-mercado-gaucho-001]  # Reemplaza con el nombre de tu bucket

images:
  - 'gcr.io/$PROJECT_ID/mercado-gaucho'
