steps:
  # Paso 1: Instalar dependencias de npm
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Paso 2: Ejecutar la compilación
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

options:
  # Usar el bucket de logs que has creado
  logs_bucket: gs://logs-mercado-gaucho-001  # Reemplaza con tu nombre de bucket

# No se especifica imagen ya que no usas Docker
